### ISSUE TITLE
Checklist for Release 14

### ISSUE THREAD

**Issue by naeluh** [gettypubs/quire#87]
These items need to be completed for release 14

https://github.com/gettypubs/quire-starter-theme
- [x] changes to hugo template

https://github.com/gettypubs/quire-cli
- [x] release includes pandoc with epub and mobi

https://github.com/gettypubs/quire-starter
- [x] global epub variable for hugo

https://github.com/gettypubs/quire
- [x] update install and usage documentation 

All these need to be completed for the code to work properly.

**Comment by naeluh** [comment]
All these have been completed the code just need to be merged into master for release 14.

**Comment by geealbers** [comment]
Alpha 14 is released! Closing
