### ISSUE TITLE
Quire-docs checklist

### ISSUE THREAD

**Issue by mbelhu** [gettypubs/quire#91]
See the review google doc for reference: [https://docs.google.com/spreadsheets/d/1Ps-JKsvJ3tXU30EOEcGjDiXOva2O1BnHWnwxVEcTOdg/edit#gid=291568003](https://docs.google.com/spreadsheets/d/1Ps-JKsvJ3tXU30EOEcGjDiXOva2O1BnHWnwxVEcTOdg/edit#gid=291568003)

**Pages TK**
- [ ] "Copyright and about pages" page to be written
- [ ] "Zooming Images & Maps" page to be written
- [ ] "Multiformat output" this page only contains info about Github licensing 
- [ ] Publication and configuration metadata mentions (and links to) a revision history policy document that doesn't exist yet

**Content TK**
- [ ] Content page types (data and search) information in "pages & plain" page needs to be written
- [ ] Creating a new Quire theme section in "Styles customization" page
- [ ] "Using GitHub to Manage Changes to Your Project" and "Using GitHub to Collaborate with Others on Your Project" sections on "Github for Quire page
- [ ] As of now, only a few pages have no introduction summarizing the content. Add it to the ones missing

**Other**
- [ ] Title of "Pages & Plain text" can be more descriptive
- [ ] "What Do the Quire Repositories Do?" section on the "About" page could have its own page. The other info on this page could be part of an introduction 
- [ ] "Collections catalogue page" describe four classes for 'contents' page type.  Differences between the classes `"abstract"`, `"grid"` and `"list"` are clear when tested with sample content but `"brief"` looks the same as `"list"`. These classes need further description and maybe additional screenshots.

**Comment by geealbers** [comment]
In process, but closing as stale
